name: android_with_firebase
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.1
  get: ^4.6.5
  get_storage: ^2.1.1
  firebase_storage: ^11.3.1
  firebase_messaging: ^14.7.1
  table_calendar: ^3.0.9
  intl: ^0.18.1
  image_picker: ^1.0.4
  type_text: ^1.0.5
  flutter_svg: ^1.1.6
  barcode_widget: ^2.0.4
  flip_card: ^0.7.0
  file_picker: ^4.6.1
  permission_handler: ^11.0.0
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Icons/
