// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOsniUT7RIxicF-Yw1jxVwCRGz6fZOCyk',
    appId: '1:232649223489:web:6d9aa71751e4c26e1345c0',
    messagingSenderId: '232649223489',
    projectId: 'android-with-firebase-32605',
    authDomain: 'android-with-firebase-32605.firebaseapp.com',
    databaseURL: 'https://android-with-firebase-32605-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'android-with-firebase-32605.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDghhp1nvOZ3jT8KJcyHOSemgpmryNCjDQ',
    appId: '1:232649223489:android:3beb843372157b121345c0',
    messagingSenderId: '232649223489',
    projectId: 'android-with-firebase-32605',
    databaseURL: 'https://android-with-firebase-32605-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'android-with-firebase-32605.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE5zz5TycYCC5d186jws5wirEm6KdIifs',
    appId: '1:232649223489:ios:002a00708f8b0f6e1345c0',
    messagingSenderId: '232649223489',
    projectId: 'android-with-firebase-32605',
    databaseURL: 'https://android-with-firebase-32605-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'android-with-firebase-32605.appspot.com',
    iosBundleId: 'com.example.androidWithFirebase',
  );
}
